Repository ssg-240304-java2/final-whiskey, pull requests merged in 2024-08, with the labels that each got.

#69 [devel]Storage Object 파일업로드
  build.gradle
  libs/RestFileUploadLib-0.2.1-SNAPSHOT.jar
Labels: api

#70 [UI/Backend] 프론트엔드 전반적인 개선 및 기능 추가, Storage Object 파일업로드 라이브러리 적용
  .github/workflows/docker-image.yml
  .gitignore
  build.gradle
  build/resources/main/templates/main.html
  build/resources/main/templates/sub.html
  build/tmp/compileJava/previous-compilation-data.bin
  libs/RestFileUploadLib-0.2.1-SNAPSHOT.jar
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/resources/static/css/common.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/mainPage.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/receiptVerification.css
  src/main/resources/static/css/register-store.css
  src/main/resources/static/css/register.css
  src/main/resources/static/css/restaurantDetail.css
  src/main/resources/static/css/searchResults.css
  src/main/resources/static/css/writeReview.css
  src/main/resources/static/js/register-store.js
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/static/js/searchResults.js
  src/main/resources/templates/fragments/banner.html
  src/main/resources/templates/fragments/categoryFilter.html
  src/main/resources/templates/fragments/categoryModal.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/inquiryItem.html
  src/main/resources/templates/fragments/menuItem.html
  src/main/resources/templates/fragments/modal.html
  src/main/resources/templates/fragments/mypage_contentSection.html
  src/main/resources/templates/fragments/mypage_editProfileModal.html
  src/main/resources/templates/fragments/mypage_profileHeader.html
  src/main/resources/templates/fragments/mypage_sidebar.html
  src/main/resources/templates/fragments/photoUpload.html
  src/main/resources/templates/fragments/restaurantBanner.html
  src/main/resources/templates/fragments/restaurantCard.html
  src/main/resources/templates/fragments/resultCard.html
  src/main/resources/templates/fragments/reviewItem.html
  src/main/resources/templates/fragments/reviewSubmitButtons.html
  src/main/resources/templates/fragments/reviewTextarea.html
  src/main/resources/templates/fragments/starRating.html
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/receiptVerification.html
  src/main/resources/templates/register-store.html
  src/main/resources/templates/register.html
  src/main/resources/templates/restaurantDetail.html
  src/main/resources/templates/searchResults.html
  src/main/resources/templates/sub.html
  src/main/resources/templates/writeReview.html
Labels: Feat., UI/UX, api

#79 devel 브랜치 -> main merge
  .github/workflows/docker-image.yml
  build.gradle
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/whiskey/rvcom/entity/favorite/Favorite.java
  src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiry.java
  src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiryResponse.java
  src/main/java/com/whiskey/rvcom/entity/member/LoginType.java
  src/main/java/com/whiskey/rvcom/entity/member/Member.java
  src/main/java/com/whiskey/rvcom/entity/member/Role.java
  src/main/java/com/whiskey/rvcom/entity/report/Report.java
  src/main/java/com/whiskey/rvcom/entity/report/RestaurantReport.java
  src/main/java/com/whiskey/rvcom/entity/report/ReviewCommentReport.java
  src/main/java/com/whiskey/rvcom/entity/report/ReviewReport.java
  src/main/java/com/whiskey/rvcom/entity/resource/ImageFile.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/Address.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/OpenCloseTime.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/Restaurant.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/RestaurantCategory.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/RestaurantNotice.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/WeeklyOpenCloseTime.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/menu/Menu.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/registration/RegistrationStatus.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/registration/RestaurantRegistrationApplication.java
  src/main/java/com/whiskey/rvcom/entity/review/Rating.java
  src/main/java/com/whiskey/rvcom/entity/review/Review.java
  src/main/java/com/whiskey/rvcom/entity/review/ReviewComment.java
  src/main/java/com/whiskey/rvcom/entity/review/ReviewImage.java
  src/main/java/com/whiskey/rvcom/entity/review/ReviewLike.java
  src/main/resources/application.yml
  src/main/resources/static/css/register-store.css
  src/main/resources/static/css/register.css
  src/main/resources/static/css/restaurantDetail.css
  src/main/resources/static/js/register-store.js
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/templates/register-store.html
  src/main/resources/templates/register.html
  src/main/resources/templates/restaurantDetail.html
Labels: UI/UX

#94 feat(report): 신고 엔티티 매핑을 위한 jap 레포지토리 3개 추가 #86
  src/main/java/com/whiskey/rvcom/entity/repository/RestaurantReportRepository.java
  src/main/java/com/whiskey/rvcom/entity/repository/ReviewCommentReportRepository.java
  src/main/java/com/whiskey/rvcom/entity/repository/ReviewReportRepository.java
Labels: Feat.

#90 feat: 리포지토리 모듈 추가 #88
  src/main/java/com/whiskey/rvcom/repository/RestaurantInquiryRepository.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantNoticeRepository.java
Labels: Feat.

#93 [FEAT] Favorite 및 ImageFile 엔티티를 위한 Repository 인터페이스 추가 #87
  src/main/java/com/whiskey/rvcom/repository/FavoriteRepository.java
  src/main/java/com/whiskey/rvcom/repository/ImageFileRepository.java
Labels: Feat.

#95 feat(report): 신고 기능 구현을 위한 엔티티-DTO간 매핑 레포지토리 생성 #86
  src/main/java/com/whiskey/rvcom/entity/repository/RestaurantReportRepository.java
  src/main/java/com/whiskey/rvcom/entity/repository/ReviewCommentReportRepository.java
  src/main/java/com/whiskey/rvcom/entity/repository/ReviewReportRepository.java
Labels: Feat.

#98 Feat(modelmapperregist): ModelMapper 사용을 위한 의존성 주입 + report의 repository 위치 수정
  build.gradle
  src/main/java/com/whiskey/rvcom/config/AppConfig.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantReportRepository.java
  src/main/java/com/whiskey/rvcom/repository/ReviewCommentReportRepository.java
  src/main/java/com/whiskey/rvcom/repository/ReviewReportRepository.java
Labels: enhancement

#99 feat: 회원 Repository 생성 #83
  src/main/java/repository/MemberRepository.java
Labels: Feat.

#100 엔티티 매퍼 객체에 프로퍼티 속성 부여
  src/main/java/com/whiskey/rvcom/entity/favorite/Favorite.java
  src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiry.java
  src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiryResponse.java
  src/main/java/com/whiskey/rvcom/entity/member/Member.java
  src/main/java/com/whiskey/rvcom/entity/report/Report.java
  src/main/java/com/whiskey/rvcom/entity/report/RestaurantReport.java
  src/main/java/com/whiskey/rvcom/entity/report/ReviewCommentReport.java
  src/main/java/com/whiskey/rvcom/entity/report/ReviewReport.java
  src/main/java/com/whiskey/rvcom/entity/resource/ImageFile.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/Address.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/OpenCloseTime.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/Restaurant.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/RestaurantNotice.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/WeeklyOpenCloseTime.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/menu/Menu.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/registration/RestaurantRegistrationApplication.java
  src/main/java/com/whiskey/rvcom/entity/review/Review.java
  src/main/java/com/whiskey/rvcom/entity/review/ReviewComment.java
  src/main/java/com/whiskey/rvcom/entity/review/ReviewImage.java
  src/main/java/com/whiskey/rvcom/entity/review/ReviewLike.java
Labels: database

#101 feat: 음식점 관련 레포지터리 모듈 추가 #84
  src/main/java/com/whiskey/rvcom/repository/MenuRepository.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantRegistrationRepository.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantRepository.java
Labels: Feat.

#108 feat: 쿼리메서드 작성
  src/main/java/com/whiskey/rvcom/repository/RestaurantInquiryRepository.java
Labels: Feat.

#105 Feat/favorite -> devel 브랜치 머지
  src/main/java/com/whiskey/rvcom/repository/FavoriteRepository.java
Labels: Feat.

#104 feat(Report): 식당신고목록 전체조회 메서드
  src/main/java/com/whiskey/rvcom/config/AppConfig.java
  src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
  src/main/java/com/whiskey/rvcom/report/model/dto/RestaurantDTO.java
  src/main/java/com/whiskey/rvcom/report/model/dto/RestaurantReportDTO.java
  src/main/java/com/whiskey/rvcom/report/model/dto/ReviewCommentReportDTO.java
  src/main/java/com/whiskey/rvcom/report/model/dto/ReviewReportDTO.java
  src/main/java/com/whiskey/rvcom/report/service/ReportService.java
  src/main/resources/templates/restaurantDetail.html
  src/test/java/com/whiskey/rvcom/ReportTest.java
Labels: Feat.

#107 리뷰/리뷰댓글 관련 중간 PR
  src/main/java/com/whiskey/rvcom/repository/ReviewCommentRepository.java
  src/main/java/com/whiskey/rvcom/repository/ReviewRepository.java
  src/main/java/com/whiskey/rvcom/review/ReviewCommentService.java
  src/main/java/com/whiskey/rvcom/review/ReviewController.java
  src/main/java/com/whiskey/rvcom/review/ReviewService.java
  src/test/java/com/whiskey/rvcom/review/ReviewServiceTest.java
Labels: database

#116 feat(Report): 리뷰신고목록 전체조회 메서드 및 기능 구현 시 필요한 DTO 생성 #115
  src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
  src/main/java/com/whiskey/rvcom/report/model/dto/RestaurantReportDTO.java
  src/main/java/com/whiskey/rvcom/report/model/dto/ReviewCommentDTO.java
  src/main/java/com/whiskey/rvcom/report/model/dto/ReviewCommentReportDTO.java
  src/main/java/com/whiskey/rvcom/report/model/dto/ReviewDTO.java
  src/main/java/com/whiskey/rvcom/report/service/ReportService.java
  src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
  src/test/java/com/whiskey/rvcom/ReportTest.java
  src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
  src/test/java/com/whiskey/rvcom/report/ReviewCommentReportTest.java
  src/test/java/com/whiskey/rvcom/report/ReviewReportTest.java
Labels: Feat.

#121 검색결과 페이지에 카카오지도 렌더링 및 사용자의 현위치 표시 기능 구현
  src/main/java/com/whiskey/rvcom/api/KakaoApi.java
  src/main/resources/application.yml
  src/main/resources/static/js/kakaoMapApiSource.js
  src/main/resources/static/js/kakaoMapView.js
  src/main/resources/templates/searchResults.html
Labels: Feat., api

#129 feat(Favorite): 즐겨찾기 CRUD 기능 구현 및 관련 API 확장
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/whiskey/rvcom/favorite/FavoriteController.java
  src/main/java/com/whiskey/rvcom/favorite/FavoriteService.java
  src/main/java/com/whiskey/rvcom/repository/FavoriteRepository.java
  src/test/java/com/whiskey/rvcom/favorite/FavoriteControllerTest.java
  src/test/java/com/whiskey/rvcom/favorite/FavoriteServiceTest.java
Labels: Feat., api

#139 메인페이지에서 사용자의 현재 위치 정보 보여주는 기능 구현
  src/main/resources/static/js/kakaoMapCurrentLocation.js
  src/main/resources/templates/fragments/banner.html
  src/main/resources/templates/mainPage.html
Labels: Feat., api

#141 문의 목록, 문의 작성
  src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiry.java
  src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiryReply.java
  src/main/java/com/whiskey/rvcom/entity/receipt/PaidItem.java
  src/main/java/com/whiskey/rvcom/entity/receipt/ReceiptData.java
  src/main/java/com/whiskey/rvcom/entity/report/RestaurantReport.java
  src/main/java/com/whiskey/rvcom/entity/report/ReviewCommentReport.java
  src/main/java/com/whiskey/rvcom/entity/report/ReviewReport.java
  src/main/java/com/whiskey/rvcom/entity/review/Review.java
  src/main/java/com/whiskey/rvcom/entity/review/ReviewLike.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
  src/main/java/com/whiskey/rvcom/report/model/dto/RestaurantInquiryReplyResponseDTO.java
  src/main/java/com/whiskey/rvcom/report/model/dto/RestaurantInquiryRequestDTO.java
  src/main/java/com/whiskey/rvcom/report/model/dto/RestaurantInquiryResponseDTO.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantInquiryRepository.java
  src/test/java/com/whiskey/rvcom/inquiry/RestaurantInquiryServiceTest.java
Labels: Feat.

#142 feat(report): 신고 처리 로직을 위한 신고 1개만 조회하기 #140
  src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
  src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
  src/test/java/com/whiskey/rvcom/report/ReviewCommentReportTest.java
  src/test/java/com/whiskey/rvcom/report/ReviewReportTest.java
Labels: Feat.

#145 feat: 음식점 상세 조회 페이지에서 해당 음식점의 위치를 확인할 수 있도록 지도 표시 기능 구현
  src/main/resources/static/js/kakaoMapDetailView.js
  src/main/resources/templates/restaurantDetail.html
Labels: Feat., api

#152 refactor(report): 코드 정리 commit 입니다.
  src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
  src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
  src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
  src/test/java/com/whiskey/rvcom/report/ReviewCommentReportTest.java
  src/test/java/com/whiskey/rvcom/report/ReviewReportTest.java
Labels: refactor

#164 feat(search-results): 검색 결과 페이지 UI 개선 및 반응형 디자인 구현
  src/main/resources/static/css/searchResults.css
  src/main/resources/static/js/searchResults.js
  src/main/resources/templates/searchResults.html
Labels: UI/UX, Fix

#171 feat: 음식점 공지사항 조회 및 작성 기능 구현 (#169, #170)
  src/main/java/com/whiskey/rvcom/entity/restaurant/RestaurantNotice.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeController.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
  src/main/java/com/whiskey/rvcom/notice/dto/RestaurantNoticeRequestDTO.java
  src/main/java/com/whiskey/rvcom/notice/dto/RestaurantNoticeResponseDTO.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantNoticeRepository.java
  src/test/java/com/whiskey/rvcom/notice/RestaurantNoticeServiceTest.java
Labels: Feat.

#180 feat: enum 타입(음식점 카테고리) 추가 및 엔티티 cascade 설정 변경
  src/main/java/com/whiskey/rvcom/entity/restaurant/Restaurant.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/RestaurantCategory.java
Labels: Feat.

#173 ui/ux + feat(report): 식당 신고 메서드 수정
  build/resources/main/templates/main.html
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
  src/main/java/com/whiskey/rvcom/review/dto/ReviewDTO.java
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/templates/adminMain.html
  src/main/resources/templates/adminReport.html
  src/main/resources/templates/fragments/adminHeader.html
  src/main/resources/templates/fragments/adminSideBar.html
  src/main/resources/templates/fragments/reviewItem.html
  src/main/resources/templates/main.html
  src/main/resources/templates/report/restaurantReport.html
  src/main/resources/templates/restaurantDetail.html
Labels: Feat., UI/UX

#188 Uiux/owner -> devel 점주 관리자 대시보드 기능 구현 및 UI 개선
  build/resources/main/templates/main.html
  src/main/java/com/whiskey/rvcom/controller/OwnerFragmentController.java
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/resources/static/css/owner-dashboard.css
  src/main/resources/static/js/owner-dashboard.js
  src/main/resources/static/js/restaurant-info.js
  src/main/resources/templates/fragments/owner/dashboard.html
  src/main/resources/templates/fragments/owner/inquiries.html
  src/main/resources/templates/fragments/owner/menu-management.html
  src/main/resources/templates/fragments/owner/notices.html
  src/main/resources/templates/fragments/owner/restaurant-info.html
  src/main/resources/templates/main.html
  src/main/resources/templates/owner/dashboard.html
Labels: Feat., UI/UX

#194 feat(owner): 점주 대시보드 메뉴 관리 기능 구현 #193
  build/resources/main/templates/main.html
  src/main/resources/static/css/owner-dashboard.css
  src/main/resources/static/css/restaurantDetail.css
  src/main/resources/static/js/menu-management.js
  src/main/resources/static/js/owner-dashboard.js
  src/main/resources/templates/fragments/owner/menu-management.html
  src/main/resources/templates/owner/dashboard.html
Labels: Feat., UI/UX

#199 영수증데이터 수집 및 마이그레이션 로직 추가
  src/main/java/com/whiskey/rvcom/entity/receipt/PaidItem.java
  src/main/java/com/whiskey/rvcom/entity/receipt/ReceiptData.java
  src/main/java/com/whiskey/rvcom/review/ReviewController.java
  src/main/java/com/whiskey/rvcom/review/ReviewService.java
  src/main/java/com/whiskey/rvcom/review/receipt/ReceiptMapper.java
  src/main/java/com/whiskey/rvcom/util/ocr/model/receipt/ReceiptResponse.java
  src/test/java/com/whiskey/rvcom/review/ReceiptOcrRequestTest.java
Labels: enhancement

#202 (Uiux/refactor)음식점 상세 페이지 리팩토링 및 기능 개선
  src/main/resources/static/css/restaurantDetail.css
  src/main/resources/static/css/restaurantDetail/info.css
  src/main/resources/static/css/restaurantDetail/inquiries.css
  src/main/resources/static/css/restaurantDetail/notices.css
  src/main/resources/static/css/restaurantDetail/reviews.css
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/static/js/restaurantDetail/info.js
  src/main/resources/static/js/restaurantDetail/inquiries.js
  src/main/resources/static/js/restaurantDetail/notices.js
  src/main/resources/static/js/restaurantDetail/reviews.js
  src/main/resources/templates/fragments/modal.html
  src/main/resources/templates/fragments/restaurantDetail/info.html
  src/main/resources/templates/fragments/restaurantDetail/inquiries.html
  src/main/resources/templates/fragments/restaurantDetail/notices.html
  src/main/resources/templates/fragments/restaurantDetail/reviews.html
  src/main/resources/templates/restaurantDetail.html
Labels: UI/UX, refactor

#203 리뷰 페이지 컨트롤러 기반 수정
  src/main/java/com/whiskey/rvcom/review/ReviewController.java
Labels: enhancement

#206 Fix(report): DTO->Entity #205
  src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
  src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/templates/report/restaurantdetail.html
  src/main/resources/templates/report/restaurantreport.html
  src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
Labels: Fix

#204 전달받은 id에 대응되는 음식점 정보를 반환하는 메서드 구현
  src/main/java/com/whiskey/rvcom/entity/restaurant/OpenCloseTime.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantRepository.java
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/resources/static/js/currentLocationMain.js
  src/main/resources/static/js/kakaoMapCurrentLocation.js
  src/main/resources/templates/mainPage.html
Labels: Feat.

#209 문의 답변 관련 기능 구현
  src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiry.java
  src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiryReply.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
  src/main/java/com/whiskey/rvcom/inquiry/reply/RestaurantInquiryReplyRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/reply/RestaurantInquiryReplyService.java
  src/main/java/com/whiskey/rvcom/inquiry/reply/dto/RestaurantInquiryReplyRequestDTO.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantInquiryReplyRepository.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantInquiryRepository.java
  src/test/java/com/whiskey/rvcom/inquiry/RestaurantInquiryServiceTest.java
  src/test/java/com/whiskey/rvcom/inquiry/reply/RestaurantInquiryReplyServiceTest.java
Labels: Feat.

#211 Feat(report): 식당신고 전체조회 페이징 적용 #210
  src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
  src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantReportRepository.java
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/report/restaurantdetail.html
  src/main/resources/templates/report/restaurantreport.html
  src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
  src/test/java/com/whiskey/rvcom/report/ReviewReportTest.java
Labels: Feat.

#215 (Uiux/refactor) [업무요청] 레스토랑 상세 페이지 동적 탭 로딩 및 URL 구조 개선
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/resources/static/css/restaurantDetail/inquiries.css
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/templates/restaurantDetail.html
Labels: Feat., UI/UX, refactor

#216 refactor(restaurantCard): 상세 정보 버튼 텍스트 수정
  src/main/resources/templates/fragments/restaurantCard.html
Labels: UI/UX

#217 검색결과 페이지의 카카오지도가 div를 벗어나는 문제 해결
  src/main/resources/static/css/searchResults.css
Labels: Fix

#218 Fix(report): 식당 신고하기 모달폼 세부 조정입니다.
  src/main/resources/templates/restaurantDetail.html
Labels: Fix

#222 main page에서 사용자의 위치와의 거리 순으로 모든 음식점 출력 기능 구현
  src/main/resources/static/js/currentLocationMain.js
  src/main/resources/templates/mainPage.html
Labels: Feat.

#235 음식점 상세 페이지에서 음식점의 정보를 받아와 표시
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/resources/static/js/currentLocationMain.js
  src/main/resources/static/js/kakaoMapDetailView.js
  src/main/resources/templates/fragments/restaurantBanner.html
  src/main/resources/templates/restaurantDetail.html
Labels: Feat.

#237 음식점 공지사항 조회 기능 web 연동
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeController.java
  src/main/resources/static/js/restaurantDetail/notices.js
Labels: Feat.

#236 (Feat/imageFile) MultipartFile 지원 및 파일 처리 개선
  src/main/java/com/whiskey/rvcom/ImageFile/ImageFileService.java
  src/test/java/com/whiskey/rvcom/ImageFile/ImageFileServiceTest.java
Labels: Feat., api

#238 fix: 누락된 div 추가
  src/main/resources/templates/restaurantDetail.html
Labels: Feat.

#240 누락된 div 추가
  src/main/resources/static/js/restaurantDetail.js
Labels: bug, Fix

#242 Fix(report): 식당 상세보기 오류 해결 #241
  src/main/resources/static/js/restaurantDetail.js
Labels: Fix

#243 Fix(report): 식당 상세보기 오류 해결 2 #241
  src/main/resources/static/js/restaurantDetail.js
Labels: Fix

#248 기존 기능 Web 연동 및 보완 pr 입니다.
  src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/templates/main.html
Labels: Feat.

#249 음식점 리뷰페이지 리뷰카드 정보 바인딩 작업 수행
  src/main/java/com/whiskey/rvcom/entity/review/Review.java
  src/main/java/com/whiskey/rvcom/review/ReviewController.java
  src/main/resources/templates/fragments/restaurantDetail/reviews.html
  src/main/resources/templates/fragments/reviewItem.html
Labels: enhancement

#230 feat: 멤버 기능, 설정파일, UI/UX
  build.gradle
  src/main/java/com/whiskey/rvcom/ImageFile/ImageFileService.java
  src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
  src/main/java/com/whiskey/rvcom/Member/emailauth/EmailService.java
  src/main/java/com/whiskey/rvcom/Member/emailauth/RequestHandler.java
  src/main/java/com/whiskey/rvcom/Member/emailauth/RequestObject.java
  src/main/java/com/whiskey/rvcom/Member/exception/BadRequestException.java
  src/main/java/com/whiskey/rvcom/Member/exception/GlobalExceptionHandler.java
  src/main/java/com/whiskey/rvcom/Member/exception/NotFoundException.java
  src/main/java/com/whiskey/rvcom/Member/handler/CustomLogoutSuccessHandler.java
  src/main/java/com/whiskey/rvcom/Member/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/whiskey/rvcom/Member/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/whiskey/rvcom/Member/oauth2/CustomOAuth2User.java
  src/main/java/com/whiskey/rvcom/Member/oauth2/OAuth2Attributes.java
  src/main/java/com/whiskey/rvcom/Member/oauth2/Provider.java
  src/main/java/com/whiskey/rvcom/Member/service/CustomOAuth2AuthService.java
  src/main/java/com/whiskey/rvcom/Member/service/CustomOidcUserService.java
  src/main/java/com/whiskey/rvcom/Member/service/MemberManagementService.java
  src/main/java/com/whiskey/rvcom/Member/service/SocialLoginService.java
  src/main/java/com/whiskey/rvcom/Member/service/VerificationService.java
  src/main/java/com/whiskey/rvcom/config/AppConfig.java
  src/main/java/com/whiskey/rvcom/config/OAuth2SuccessHandlerConfig.java
  src/main/java/com/whiskey/rvcom/config/SecurityConfig.java
  src/main/java/com/whiskey/rvcom/config/WebConfig.java
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/repository/MemberRepository.java
  src/main/resources/application.yml
  src/main/resources/static/css/login.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/register.css
  src/main/resources/static/images/btnG_complete.png
  src/main/resources/static/images/web_neutral.png
  src/main/resources/static/js/register.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/mypage_contentSection.html
  src/main/resources/templates/fragments/mypage_editProfileModal.html
  src/main/resources/templates/fragments/mypage_editProfileModal_basic.html
  src/main/resources/templates/fragments/mypage_editProfileModal_social.html
  src/main/resources/templates/fragments/mypage_profileHeader.html
  src/main/resources/templates/fragments/mypage_sidebar.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/register.html
  src/main/resources/templates/register_basic.html
  src/main/resources/templates/register_social.html
  src/test/java/com/whiskey/rvcom/ImageFile/ImageFileServiceTest.java
  src/test/java/com/whiskey/rvcom/Member/MemberRegistrationTest.java
  src/test/java/com/whiskey/rvcom/Member/SocialRegisterControllerTest.java
Labels: Feat., UI/UX, api

#253 feat: 음식점 상세 페이지에서 음식점의 정보를 받아와 표시 기능 구현
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/repository/MenuRepository.java
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/resources/static/css/restaurantDetail.css
  src/main/resources/static/js/currentLocationMain.js
  src/main/resources/templates/fragments/restaurantBanner.html
  src/main/resources/templates/fragments/restaurantDetail/info.html
  src/main/resources/templates/restaurantDetail.html
Labels: Feat.

#256 음식점 문의 조회 기능 web 연동
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/resources/static/js/restaurantDetail/inquiries.js
  src/main/resources/templates/fragments/inquiryItem.html
  src/main/resources/templates/fragments/modal.html
  src/main/resources/templates/fragments/restaurantDetail/inquiries.html
  src/main/resources/templates/restaurantDetail.html
  src/test/java/com/whiskey/rvcom/notice/RestaurantNoticeServiceTest.java
Labels: Feat.

#252 feat: 일반 회원정보 수정 구현
  src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
  src/main/java/com/whiskey/rvcom/Member/emailauth/EmailService.java
  src/main/java/com/whiskey/rvcom/Member/emailauth/RequestHandler.java
  src/main/java/com/whiskey/rvcom/Member/emailauth/RequestObject.java
  src/main/java/com/whiskey/rvcom/Member/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/whiskey/rvcom/Member/service/VerificationService.java
  src/main/java/com/whiskey/rvcom/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/register.css
  src/main/resources/static/js/register.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/mypage_editProfileModal_basic.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/register_basic.html
Labels: bug, Feat., UI/UX, api

#259 Feat(businessRegist): 입점신청 사용자등록증 진위여부 확인 #257
  .github/workflows/docker-image.yml
  src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
  src/main/java/com/whiskey/rvcom/businessregister/model/dto/BusinessRequestHead.java
  src/main/java/com/whiskey/rvcom/businessregister/model/dto/ResponseBody.java
  src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
  src/main/resources/application.yml
  src/main/resources/static/js/register-store.js
  src/main/resources/templates/register-store.html
Labels: Feat., api

#261 fix: 음식점 목록을 불러올 때 데이터 양의 과다로 인해 음식점 데이터를 불러오지 못하는 문제 해결
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/java/com/whiskey/rvcom/restaurant/dto/RestaurantCardDTO.java
  src/main/resources/static/js/currentLocationMain.js
Labels: Feat.

#264 Fix(report): SyntaxError 해결 시도용
  src/main/resources/templates/report/reviewreport.html
Labels: Fix

#265 음식점 목록 데이터 및 음식점 상세정보 페이지 불러오지 못하는 문제 해결
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/java/com/whiskey/rvcom/review/ReviewController.java
  src/main/java/com/whiskey/rvcom/review/ReviewService.java
  src/main/resources/templates/fragments/restaurantDetail/reviews.html
  src/main/resources/templates/restaurantDetail.html
Labels: Fix

#268 문의 작성 기능 web 연동
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
  src/main/java/com/whiskey/rvcom/inquiry/dto/RestaurantInquiryRequestDTO.java
  src/main/resources/static/js/restaurantDetail/inquiries.js
  src/main/resources/templates/fragments/restaurantDetail/inquiries.html
  src/test/java/com/whiskey/rvcom/inquiry/RestaurantInquiryServiceTest.java
Labels: Feat.

#269 상세정보 페이지 매핑 메소드 기능 분산
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
Labels: Feat.

#270 메인페이지와 test 페이지 스왑
  src/main/java/com/whiskey/rvcom/misc/TestController.java
Labels: Feat.

#272 [uiux/refactor] 메인 페이지 UI/UX 개선 및 위치 기반 기능 강화
  src/main/resources/static/css/mainPage.css
  src/main/resources/static/js/currentLocationMain.js
  src/main/resources/templates/fragments/banner.html
  src/main/resources/templates/mainPage.html
Labels: enhancement, Feat., UI/UX

#274 Feat(businessRegist): 입점신청 등록 프로세스 완료 #273
  src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
  src/main/java/com/whiskey/rvcom/businessregister/model/dto/MyResponseBody.java
  src/main/java/com/whiskey/rvcom/businessregister/model/dto/RegistInfo.java
  src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
  src/main/resources/static/js/register-store.js
  src/main/resources/templates/admin/registrestaurant.html
  src/main/resources/templates/register-store.html
Labels: Feat.

#276 공지사항 작성 기능 web 연동
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeController.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
  src/main/resources/static/js/restaurantDetail/notices.js
  src/main/resources/templates/restaurantDetail.html
Labels: Feat.

#279 Feat(businessRegist): 입점신청 목록 전체 조회 2 #275
  src/main/resources/templates/admin/adminMain.html
Labels: Fix

#281 Fix(businessRegist): 입점신청 목록 전체 조회 오류 해결 #280
  src/main/resources/templates/admin/registrestaurant.html
Labels: Fix

#284 Fix(report): 리뷰 신고 목록 조회 매핑 문제 해결 #283
  src/main/java/com/whiskey/rvcom/entity/review/Review.java
  src/main/java/com/whiskey/rvcom/entity/review/ReviewLike.java
  src/main/resources/static/js/admin/review-report.js
  src/main/resources/templates/admin/fragments/report-management.html
  src/main/resources/templates/report/reviewreport.html
Labels: Fix

#288 Fix(report) 리뷰, 댓글 신고 처벌 결정에 따른 상태값 변경 메서드
  src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
Labels: Fix

#292 검색 시 검색 내용에 연관된 음식점 표시
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantRepository.java
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/java/com/whiskey/rvcom/restaurant/controller/restaurantController.java
  src/main/java/com/whiskey/rvcom/restaurant/dto/RestaurantSearchResultDTO.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/resources/static/js/kakaoMapSearchResultView.js
  src/main/resources/static/js/kakaoMapView.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/resultCard.html
  src/main/resources/templates/searchResults.html
Labels: Feat.

#290 Fix: 자잘한 세부 조정 입니다.
  src/main/resources/templates/admin/adminMain.html
  src/main/resources/templates/admin/registrestaurant.html
  src/main/resources/templates/report/restaurantreport.html
  src/main/resources/templates/report/reviewcommentreport.html
  src/main/resources/templates/report/reviewreport.html
Labels: Fix

#295 입점 프로세스 : 세부조회, 처리기능
  src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
  src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
  src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
  src/main/resources/templates/admin/regist-detail.html
  src/main/resources/templates/admin/registrestaurant.html
  src/main/resources/templates/report/reviewcommentreport.html
Labels: Feat.

#289 [ui/ux] 음식점 상세 페이지 신고 기능 개선 및 UI/UX 리팩토링
  src/main/resources/static/css/restaurantDetail.css
  src/main/resources/static/css/restaurantDetail/reviews.css
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/templates/fragments/restaurantDetail/info.html
  src/main/resources/templates/fragments/reviewItem.html
  src/main/resources/templates/restaurantDetail.html
Labels: enhancement, Feat., UI/UX, refactor

#297 문의 삭제 기능 web 연동과 문의 조회 부분 수정
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
  src/main/java/com/whiskey/rvcom/inquiry/dto/RestaurantInquiryResponseDTO.java
  src/main/resources/static/js/restaurantDetail/inquiries.js
  src/main/resources/templates/fragments/inquiryItem.html
Labels: Feat., refactor

#296 refactor: DTO에 id와 삭제여부 필드 추가 및 매핑 업데이트
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
  src/main/java/com/whiskey/rvcom/notice/dto/RestaurantNoticeResponseDTO.java
  src/main/resources/templates/fragments/restaurantDetail/notices.html
Labels: refactor

#300 feat(admin): 신고 처리 UI 개선 및 기능 강화
  src/main/resources/static/css/admin/admin-dashboard.css
  src/main/resources/static/js/admin/comment-report.js
  src/main/resources/static/js/admin/restaurant-report.js
  src/main/resources/static/js/admin/review-report.js
  src/main/resources/templates/admin/fragments/report-management.html
Labels: Feat., UI/UX, refactor

#301 feat(admin): 관리자 페이지 입점 관리 기능 추가 (#258)
  src/main/java/com/whiskey/rvcom/controller/AdminController.java
  src/main/resources/static/js/admin/admin-dashboard.js
  src/main/resources/static/js/admin/restaurant-management.js
  src/main/resources/templates/admin/adminMain.html
  src/main/resources/templates/admin/fragments/restaurant-management.html
Labels: Feat., UI/UX

#302 뷰 id 바인딩 문법 오류 긴급수정
  src/main/resources/templates/fragments/reviewItem.html
Labels: bug

#304 Feat(ReviewLike): 리뷰 좋아요 기능 구현 #303
  src/main/java/com/whiskey/rvcom/repository/ReviewLikeRepository.java
  src/main/java/com/whiskey/rvcom/review/ReviewController.java
  src/main/java/com/whiskey/rvcom/review/ReviewLikeService.java
  src/main/resources/static/js/restaurantDetail/reviews.js
  src/main/resources/templates/fragments/reviewItem.html
Labels: refactor

#306 Fix(report): 댓글 작성 후 신고하기 버튼이 달라지는 현상 해결 #305
  src/main/resources/static/js/restaurantDetail/reviews.js
Labels: Fix

#308 [Uiux/refactor] 리뷰 작성 페이지 UI 개선 및 식당 신고 관리 기능 강화
  src/main/resources/static/css/admin/admin-dashboard.css
  src/main/resources/static/css/common.css
  src/main/resources/static/css/writeReview.css
  src/main/resources/static/js/admin/restaurant-management.js
  src/main/resources/static/js/admin/restaurant-report.js
  src/main/resources/templates/admin/fragments/report-management.html
Labels: Feat., UI/UX, refactor

#307 feat: 음식점 커버 이미지 불러와 음식점 정보에 표시
  src/main/java/com/whiskey/rvcom/restaurant/controller/restaurantController.java
  src/main/java/com/whiskey/rvcom/restaurant/dto/RestaurantCardDTO.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/resources/static/css/common.css
  src/main/resources/static/js/currentLocationMain.js
  src/main/resources/templates/fragments/restaurantBanner.html
  src/main/resources/templates/restaurantDetail.html
Labels: Feat.

#313 UI 개선 및 관리자 기능 강화
  src/main/resources/static/css/header.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/register.css
  src/main/resources/static/js/admin/comment-report.js
  src/main/resources/static/js/admin/restaurant-report.js
  src/main/resources/static/js/admin/review-report.js
  src/main/resources/static/static/images/logo.png
  src/main/resources/templates/admin/fragments/report-management.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
Labels: enhancement, Feat., UI/UX, refactor

#311 Fix(report): 댓글 / 리뷰 신고버튼과 신고 등록 기능 매칭 #310
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/templates/fragments/restaurantDetail/reviews.html
  src/main/resources/templates/fragments/reviewItem.html
  src/main/resources/templates/restaurantDetail.html
Labels: Feat.

#315 feat: mainPage에서 선택된 음식점 카테고리로 분류
  src/main/java/com/whiskey/rvcom/entity/restaurant/RestaurantCategory.java
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/resources/static/js/currentLocationMain.js
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/restaurantDetail.html
Labels: Feat.

#312 feat: 회원파트
  build.gradle
  src/main/java/com/whiskey/rvcom/ImageFile/ImageFileService.java
  src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
  src/main/java/com/whiskey/rvcom/Member/exception/BadRequestException.java
  src/main/java/com/whiskey/rvcom/Member/exception/GlobalExceptionHandler.java
  src/main/java/com/whiskey/rvcom/Member/exception/NotFoundException.java
  src/main/java/com/whiskey/rvcom/Member/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/whiskey/rvcom/Member/handler/CustomLogoutSuccessHandler.java
  src/main/java/com/whiskey/rvcom/Member/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/whiskey/rvcom/Member/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/whiskey/rvcom/Member/oauth2/CustomOAuth2User.java
  src/main/java/com/whiskey/rvcom/Member/oauth2/OAuth2Attributes.java
  src/main/java/com/whiskey/rvcom/Member/oauth2/Provider.java
  src/main/java/com/whiskey/rvcom/Member/service/CustomOAuth2AuthService.java
  src/main/java/com/whiskey/rvcom/Member/service/CustomOidcUserService.java
  src/main/java/com/whiskey/rvcom/Member/service/MemberManagementService.java
  src/main/java/com/whiskey/rvcom/Member/service/SocialLoginService.java
  src/main/java/com/whiskey/rvcom/config/AppConfig.java
  src/main/java/com/whiskey/rvcom/config/OAuth2SuccessHandlerConfig.java
  src/main/java/com/whiskey/rvcom/config/SecurityConfig.java
  src/main/java/com/whiskey/rvcom/config/WebConfig.java
  src/main/java/com/whiskey/rvcom/controller/OwnerFragmentController.java
  src/main/java/com/whiskey/rvcom/favorite/FavoriteController.java
  src/main/java/com/whiskey/rvcom/favorite/FavoriteService.java
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/repository/MemberRepository.java
  src/main/resources/application.yml
  src/main/resources/static/css/login.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/register.css
  src/main/resources/static/images/btnG_complete.png
  src/main/resources/static/images/web_neutral.png
  src/main/resources/static/js/mypage.js
  src/main/resources/static/js/register.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/mypage_contentSection.html
  src/main/resources/templates/fragments/mypage_editProfileModal.html
  src/main/resources/templates/fragments/mypage_editProfileModal_basic.html
  src/main/resources/templates/fragments/mypage_editProfileModal_social.html
  src/main/resources/templates/fragments/mypage_profileHeader.html
  src/main/resources/templates/fragments/mypage_sidebar.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/owner/dashboard.html
  src/main/resources/templates/register_basic.html
  src/main/resources/templates/register_social.html
  src/test/java/com/whiskey/rvcom/ImageFile/ImageFileServiceTest.java
  src/test/java/com/whiskey/rvcom/Member/MemberRegistrationTest.java
  src/test/java/com/whiskey/rvcom/Member/SocialRegisterControllerTest.java
  src/test/java/com/whiskey/rvcom/favorite/FavoriteControllerTest.java
Labels: Feat., UI/UX, api

#329 Feat(business): 검증 성공 후 검증 정보 비활성화 기능 #327
  src/main/resources/static/js/register-store.js
  src/main/resources/templates/register-store.html
Labels: Feat.

#330 feat(favorite): 즐겨찾기 기능 구현 및 불필요한 TODO 주석 제거 (#177)
  src/main/java/com/whiskey/rvcom/favorite/FavoriteController.java
  src/main/java/com/whiskey/rvcom/favorite/FavoriteService.java
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/templates/fragments/restaurantBanner.html
Labels: Feat., api

#328 edit: 로그인, 회원가입 뷰단 로고 삽입
  src/main/resources/templates/login.html
  src/main/resources/templates/register_basic.html
  src/main/resources/templates/register_social.html
Labels: UI/UX

#333 Feat(business): 입점신청 상세보기, 승인, 거절 매칭 #332
  src/main/resources/static/js/admin/restaurant-management.js
Labels: refactor, Fix

#334 Uiux/refactor: 로고 추가 및 불필요한 코드 제거
  src/main/resources/templates/fragments/header.html
Labels: UI/UX, refactor

#336 edit: 마이페이지 버그 및 세션정보추가
  src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/fragments/mypage_contentSection.html
  src/main/resources/templates/fragments/mypage_sidebar.html
  src/main/resources/templates/mypage.html
Labels: bug, UI/UX

#337 사용자 검증 후 동적으로 활성화 되는 삭제 버튼 기능 구현
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
  src/main/java/com/whiskey/rvcom/inquiry/dto/RestaurantInquiryResponseDTO.java
  src/main/resources/static/js/restaurantDetail/inquiries.js
Labels: Feat.

#338 edit: bookmark -> favorite으로 변경됨
  src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/fragments/mypage_sidebar.html
  src/main/resources/templates/mypage.html
Labels: bug, Fix

#340 fix(assets): 로고 이미지 경로 수정 및 정리
  src/main/resources/static/images/logo.png
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/main/resources/templates/register_basic.html
  src/main/resources/templates/register_social.html
Labels: UI/UX, Fix

#344 feat: 점주 페이지에서 음식점 정보 표시
  src/main/java/com/whiskey/rvcom/repository/RestaurantRepository.java
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/java/com/whiskey/rvcom/restaurant/dto/OwnersRestaurantInfoDTO.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/resources/static/css/common.css
  src/main/resources/static/js/restaurant-info.js
  src/main/resources/templates/fragments/owner/restaurant-info.html
Labels: Feat.

#345 영수증 인증 및 리뷰 작성 프로세스 개선
  src/main/java/com/whiskey/rvcom/ImageFile/ImageFileService.java
  src/main/java/com/whiskey/rvcom/repository/ReceiptRepository.java
  src/main/java/com/whiskey/rvcom/review/ReceiptService.java
  src/main/java/com/whiskey/rvcom/review/ReceiptVerificationController.java
  src/main/resources/static/css/receiptVerification.css
  src/main/resources/static/js/restaurantDetail/reviews.js
  src/main/resources/templates/fragments/restaurantDetail/reviews.html
  src/main/resources/templates/receiptVerification.html
  src/main/resources/templates/writeReview.html
Labels: enhancement, Feat., UI/UX, api, refactor

#349 Refactor(report): 메일 발송 멘트 수정 #347
  src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
Labels: refactor

#350 style(admin): 관리자 대시보드 UI 개선 및 레스토랑 관리 기능 강화
  src/main/resources/static/css/admin/admin-dashboard.css
  src/main/resources/static/js/admin/restaurant-management.js
  src/main/resources/templates/admin/adminMain.html
  src/main/resources/templates/admin/fragments/restaurant-management.html
Labels: UI/UX, refactor, Fix

#353 문의, 공지사항 개선
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
  src/main/resources/static/js/owner/inquiries.js
  src/main/resources/static/js/owner/notices.js
  src/main/resources/templates/fragments/owner/inquiries.html
  src/main/resources/templates/fragments/owner/notices.html
Labels: Feat., refactor

#354 Feat(business): 입점신청 메일발송 기능 #351
  src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
  src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
  src/main/java/com/whiskey/rvcom/mail/MailConst.java
  src/main/java/com/whiskey/rvcom/mail/MailInfo.java
  src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
  src/main/java/com/whiskey/rvcom/report/model/dto/MailConst.java
  src/main/java/com/whiskey/rvcom/report/model/dto/MailInfo.java
  src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
Labels: Feat., api

#357 fix: Restaurant.menus와 Menu.restaurant 사이에서 발생하는 순환참조 문제 해결
  src/main/java/com/whiskey/rvcom/entity/restaurant/Restaurant.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/menu/Menu.java
Labels: Fix

#356 Feat(business): 입점신청 승인 후 레스토랑 등록 기능 #355
  src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
  src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
Labels: Feat.

#359 Refactor(report): 식당 신고 전체조회-> 처리전 #358
  src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
  src/test/java/com/whiskey/rvcom/report/ReviewReportTest.java
Labels: refactor

#365 음식점 id로 음식점 정보 받아오는 service 추가
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
Labels: Feat.

#360 feat: 점주 페이지에서 음식점 메뉴 목록 조회 기능 구현
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/resources/static/js/menu-management.js
Labels: Feat.

#363 HotFix : weekly_open_close_time NULL EXCEPTION
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
Labels: Fix

#364 공지사항 및 문의내역 페이지네이션 오류 해결
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/reply/RestaurantInquiryReplyRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/reply/RestaurantInquiryReplyService.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantOwnerNoticeController.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantNoticeRepository.java
  src/main/resources/static/js/owner/inquiries.js
  src/main/resources/static/js/owner/notices.js
  src/main/resources/templates/fragments/owner/inquiries.html
  src/main/resources/templates/fragments/owner/notices.html
Labels: Feat., refactor, Fix

#368 Refactor(business): 입점신청 전체 조회 -> 처리전 조회 #367
  src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
  src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantRegistrationRepository.java
Labels: refactor

#366 Refactor(report): 모든 신고 처리전 조회로 변경
  src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
  src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
  src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
  src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
  src/main/java/com/whiskey/rvcom/repository/ReviewCommentReportRepository.java
Labels: Feat.

#369 feat: 점주 페이지에서 음식점 id를 불러서 사용할 수 있도록 hidden input 추가
  src/main/java/com/whiskey/rvcom/controller/OwnerFragmentController.java
  src/main/resources/templates/owner/dashboard.html
Labels: Feat.

#371 Refactor(business): 입점 신청 시 로그인 세션의 memberId 사용 #370
  src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/resources/static/js/register-store.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/register-store.html
Labels: Feat.

#373 feat: 점주 페이지에서 음식점 메뉴 추가, 수정, 삭제 기능 구현
  src/main/java/com/whiskey/rvcom/entity/restaurant/menu/Menu.java
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantMenuController.java
  src/main/java/com/whiskey/rvcom/restaurant/service/MenuService.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/resources/static/js/menu-management.js
Labels: Feat.

#375 Refactor(report): 엔티티 변경에 수정사항 수정 #374
  src/main/resources/static/js/admin/review-report.js
  src/main/resources/templates/admin/fragments/report-management.html
Labels: refactor

#377 feat: 새로고침 버튼 기능 구현
  src/main/resources/static/js/currentLocationMain.js
Labels: Feat.

#378 Uiux/refactor 공통 스타일 개선: 컨테이너 패딩 및 이미지 스타일 조정
  src/main/resources/static/css/common.css
  src/main/resources/static/css/mainPage.css
Labels: enhancement, UI/UX, refactor, Fix

#376 feat: 이메일 인증 로직 구현 및 회원가입단 뷰 수정
  src/main/java/com/whiskey/rvcom/Member/controller/EmailVerificationController.java
  src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
  src/main/java/com/whiskey/rvcom/Member/dto/EmailRequest.java
  src/main/java/com/whiskey/rvcom/Member/dto/RedisRequestPayload.java
  src/main/java/com/whiskey/rvcom/Member/dto/ResponseModel.java
  src/main/java/com/whiskey/rvcom/Member/dto/VerifyPayload.java
  src/main/java/com/whiskey/rvcom/Member/service/EmailService.java
  src/main/java/com/whiskey/rvcom/config/SecurityConfig.java
  src/main/java/com/whiskey/rvcom/config/WebConfig.java
  src/main/resources/static/css/register.css
  src/main/resources/static/images/login_register_logo.png
  src/main/resources/static/js/register.js
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/main/resources/templates/register_basic.html
  src/main/resources/templates/register_social.html
Labels: question, Feat., UI/UX, api

#379 비회원 문의 내역 접근 오류 수정
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantOwnerNoticeController.java
  src/main/resources/static/js/owner/inquiries.js
  src/main/resources/static/js/owner/notices.js
  src/main/resources/static/js/restaurantDetail/inquiries.js
  src/main/resources/templates/fragments/owner/inquiries.html
Labels: refactor, Fix

#380 feat: 음식점 상세정보 페이지에서 메뉴 보여주는 방식 변경 (리스트 -> 좌우스크롤)
  src/main/resources/static/css/restaurantDetail/info.css
Labels: Feat.

#382 Feat(business): 입점신청 승인 후 USER->OWNER 변경 #381
  src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
  src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
Labels: Feat.

#384 음식점ID 동적으로 받아서 처리하도록 로직 개선
  src/main/resources/static/js/owner/inquiries.js
  src/main/resources/static/js/owner/notices.js
Labels: Feat., Fix

#385 (Uiux/refactor) 관리자 대시보드 UI/UX 전면 개선 및 모바일 대응 강화
  src/main/resources/static/css/admin/admin-dashboard.css
  src/main/resources/static/js/admin/admin-dashboard.js
  src/main/resources/templates/admin/adminMain.html
  src/main/resources/templates/admin/fragments/dashboard.html
Labels: enhancement, UI/UX, refactor, Fix

#386 feat:헤더 수정, 마이페이지 즐겨찾기 비동기처리
  src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/mypage.html
Labels: bug, UI/UX, Fix

#390 feat: 점주 페이지 초기화면에서 점주가 보유한 음식점의 이름을 표시
  src/main/resources/static/js/owner-dashboard.js
  src/main/resources/static/js/restaurant-info.js
  src/main/resources/templates/fragments/owner/dashboard.html
  src/main/resources/templates/owner/dashboard.html
Labels: Feat.

#392 feat: 점주 음식점 정보 페이지와 정보 수정 modal에서 음식점 정보 표시
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
  src/main/java/com/whiskey/rvcom/restaurant/dto/OwnersRestaurantInfoDTO.java
  src/main/resources/static/js/menu-management.js
  src/main/resources/static/js/restaurant-info.js
Labels: Feat.

#395 Feat(report): 신고 버튼 3종류 클릭 시 로그인 여부 확인 기능 주가 #394
  src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
  src/main/resources/static/js/restaurantDetail.js
  src/main/resources/static/js/restaurantDetail/info.js
Labels: Feat.

#393 Edit: 일반 회원가입시 알럿추가 및 즐겨찾기 해제 로직 수정
  src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
  src/main/resources/static/js/mypage.js
  src/main/resources/static/js/register.js
  src/main/resources/templates/fragments/mypage_profileHeader.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/register_basic.html
Labels: bug, UI/UX, Fix

#397 사용자 페이지 문의 내역 코드 수정
  src/main/resources/static/css/restaurantDetail/inquiries.css
  src/main/resources/static/js/restaurantDetail/inquiries.js
  src/main/resources/templates/fragments/inquiryItem.html
  src/main/resources/templates/fragments/restaurantDetail/inquiries.html
Labels: UI/UX, refactor

#398 Uiux/refactor 피드백 수용 및 UI/UX 개선 및 반응형 디자인 개선
  src/main/resources/static/css/header.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/owner-dashboard.css
  src/main/resources/static/css/register.css
  src/main/resources/static/js/owner-dashboard.js
  src/main/resources/static/js/owner/inquiries.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/owner/dashboard.html
  src/main/resources/templates/fragments/owner/inquiries.html
  src/main/resources/templates/fragments/owner/menu-management.html
  src/main/resources/templates/fragments/owner/notices.html
  src/main/resources/templates/fragments/restaurantDetail/info.html
  src/main/resources/templates/owner/dashboard.html
  src/main/resources/templates/restaurantDetail.html
Labels: enhancement, UI/UX, refactor, Fix

#399 feat: 음식점 상세 페이지에서 메뉴 이미지 표시 기능
  src/main/resources/static/css/restaurantDetail/info.css
  src/main/resources/templates/fragments/menuItem.html
  src/main/resources/templates/fragments/restaurantDetail/info.html
Labels: Feat.

#400 Fix/inquiry: 모달 초기화 및 이벤트 리스너 중복 등록 문제 해결
  src/main/resources/static/js/owner-dashboard.js
  src/main/resources/static/js/owner/inquiries.js
Labels: Fix

#402 사용자 페이지 공지사항 조회 코드 간결화
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeController.java
  src/main/resources/static/js/restaurantDetail/notices.js
  src/main/resources/templates/fragments/owner/notices.html
  src/main/resources/templates/fragments/restaurantDetail/notices.html
Labels: refactor

#403 점주 페이지 문의 내역, 공지사항 코드 정리
  src/main/resources/static/js/owner/inquiries.js
  src/main/resources/static/js/owner/notices.js
  src/main/resources/templates/fragments/owner/inquiries.html
Labels: refactor

#404 점주페이지 미답변 문의글 수 카운트 기능 구현
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantInquiryRepository.java
  src/main/resources/static/js/owner-dashboard.js
  src/main/resources/templates/fragments/owner/dashboard.html
Labels: Feat.

#401 feat: 관리자페이지: 회원정보 조회 및 페이지네이션,
  src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
  src/main/java/com/whiskey/rvcom/Member/service/MemberManagementService.java
  src/main/java/com/whiskey/rvcom/Member/service/SocialLoginService.java
  src/main/java/com/whiskey/rvcom/config/SecurityConfig.java
  src/main/java/com/whiskey/rvcom/controller/AdminController.java
  src/main/java/com/whiskey/rvcom/misc/TestController.java
  src/main/java/com/whiskey/rvcom/repository/MemberRepository.java
  src/main/resources/static/js/admin/user-management.js
  src/main/resources/templates/admin/adminMain.html
  src/main/resources/templates/admin/fragments/user-management.html
Labels: bug, Feat., UI/UX

#407 리뷰 작성 시 이미지 추가되도록 수정
  src/main/java/com/whiskey/rvcom/review/ReviewController.java
  src/main/java/com/whiskey/rvcom/review/ReviewService.java
Labels: Feat.

#415 사용자 페이지 문의 내역 페이지네이션 기능 구현
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/repository/RestaurantInquiryRepository.java
  src/main/resources/static/css/restaurantDetail/inquiries.css
  src/main/resources/static/js/restaurantDetail/inquiries.js
  src/main/resources/templates/fragments/restaurantDetail/inquiries.html
Labels: Feat., UI/UX

#414 feat: redirect-uri 추가
  src/main/resources/application.yml
  src/main/resources/templates/fragments/mypage_contentSection.html
  src/main/resources/templates/register_social.html
Labels: bug, Fix

#416 feat: 주간 음식점 영업시간 변경 기능 추가
  src/main/java/com/whiskey/rvcom/entity/restaurant/OpenCloseTime.java
  src/main/java/com/whiskey/rvcom/entity/restaurant/WeeklyOpenCloseTime.java
  src/main/java/com/whiskey/rvcom/restaurant/controller/restaurantController.java
  src/main/java/com/whiskey/rvcom/restaurant/dto/OperatingHourDTO.java
  src/main/java/com/whiskey/rvcom/restaurant/dto/RestaurantOperatingHoursDTO.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/resources/static/js/restaurant-info.js
Labels: Feat.

#418 점주 음식점 메뉴 수정 페이지에서 음식점 수정/삭제 버튼 사이즈 통일
  src/main/resources/static/css/owner-dashboard.css
Labels: Feat.

#419 feat: 점주 음식점 페이지에서 메뉴 이미지 입력 기능 추가
  src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantMenuController.java
  src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
  src/main/resources/static/js/menu-management.js
Labels: Feat.

#420 검색창에서 엔터 입력 시 검색되는 기능 추가
  src/main/resources/templates/fragments/header.html
Labels: Feat.

#421 refactor: 코드 일관성 및 가독성 향상을 위한 리팩토링
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
  src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
  src/main/java/com/whiskey/rvcom/notice/RestaurantOwnerNoticeController.java
Labels: refactor

#428 점주 페이지에서 오류 수정
  src/main/resources/static/js/menu-management.js
  src/main/resources/static/js/owner-dashboard.js
  src/main/resources/static/js/restaurant-info.js
  src/main/resources/templates/owner/dashboard.html
Labels: Fix

#430 feat: 음식점 검색 페이지 디자인 변경
  src/main/resources/static/css/searchResults.css
  src/main/resources/templates/fragments/resultCard.html
  src/main/resources/templates/searchResults.html
Labels: Fix

#432 Fix(report): 리뷰, 댓글 신고 고장 해결입니다. #431
  src/main/resources/static/js/restaurantDetail.js
Labels: Fix
